CREATE TABLE Person (
                        id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        name varchar(100) NOT NULL,
                        age int NOT NULL CHECK (age > 0),
                        email varchar (100) NOT NULL UNIQUE
);

INSERT INTO Person(name, age, email) VALUES ('Max', 25, 'max@mail.com');
INSERT INTO Person(name, age, email) VALUES ('Jack', 25, 'jack@mail.com');
INSERT INTO Person(name, age, email) VALUES ('Rob', 25, 'rob@mail.com');

