CREATE TABLE Person (
                        id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        name varchar(100) NOT NULL,
                        age int NOT NULL CHECK (age > 0),
                        email varchar (100) NOT NULL UNIQUE
);

ALTER TABLE person ADD COLUMN created_at timestamp, ADD COLUMN updated_at timestamp, ADD COLUMN created_who varchar;